/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.16
 * Generated at: 2017-09-19 05:05:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.zip4s.pets.dto.ProductDTO;
import java.util.ArrayList;
import com.zip4s.pets.dto.CustomerDTO;

public final class cart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.zip4s.pets.dto.ProductDTO");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("com.zip4s.pets.dto.CustomerDTO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<!-- Latest compiled and minified CSS -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/style.css\">\r\n");
      out.write("<!-- jQuery library -->\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled JavaScript -->\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("<title>Pet's</title>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction numcheck(val, jaego) {\r\n");
      out.write("\t\tif (val > jaego - 1) {\r\n");
      out.write("\t\t\talert(\"재고량이 없습니다\")\r\n");
      out.write("\t\t\tdocument.frm.ea.value = jaego\r\n");
      out.write("\t\t} else if (val < 2) {\r\n");
      out.write("\t\t\tdocument.frm.ea.value = 1\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction up(val, jaego) {\r\n");
      out.write("\t\tif (val > jaego - 1) {\r\n");
      out.write("\t\t\talert(\"재고량이 없습니다\")\r\n");
      out.write("\t\t\tdocument.frm.ea.value = jaego\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tdocument.frm.ea.value = (val / 1) + 1\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction down(val) {\r\n");
      out.write("\t\tif (val < 2) {\r\n");
      out.write("\t\t\tdocument.frm.ea.value = 1\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tdocument.frm.ea.value = val - 1\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" \t<br>\r\n");
      out.write("\t");

	CustomerDTO dto = (CustomerDTO) session.getAttribute("login_info");
		if (dto == null) {
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"Nav_menu\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li><a href=\"login\"> 로그인 </a></li>\r\n");
      out.write("\t\t\t<li><a href=\"join\">회원가입</a></li>\r\n");
      out.write("\t\t\t<li>마이페이지</li>\r\n");
      out.write("\t\t\t<li>장바구니</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");

		} else {
	
      out.write("\r\n");
      out.write("\t<div id=\"Nav_menu\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li>");
      out.print(dto.getCname());
      out.write(" 님</li>\r\n");
      out.write("\t\t\t<li><a href=\"logout\"> 로그아웃 </a></li>\r\n");
      out.write("\t\t\t<li>마이페이지</li>\r\n");
      out.write("\t\t\t<li>장바구니</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");

		}
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<br>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"Mainimg\">\r\n");
      out.write("\t\t<a href=\"/pets\"><img src=\"resources/img/main.jpg\"\r\n");
      out.write("\t\t\tstyle=\"width: 50%; height: 30%;\"></img></a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\r\n");
      out.write("\t<center>\r\n");
      out.write("\t\t<div class=\"dropdown\" >\r\n");
      out.write("        <a href=\"shopping\"><button class=\"dropbtn\">쇼핑</button></a>\r\n");
      out.write("       \r\n");
      out.write("       <form id=\"itemForm\" action=\"ProductServlet?Action=ITEM\" method=\"post\">\r\n");
      out.write("        <div class=\"dropdown-content\">\r\n");
      out.write("\t        <input type=\"submit\" id=\"item\" name=\"item\" value=\"장난감\" style=\"color: black; border: 0px; padding: 12px 36%; text-decoration: none;\r\n");
      out.write("    display: block;\">\r\n");
      out.write("\t        <input type=\"submit\" id=\"item\" name=\"item\" value=\"간식\" style=\"color: black; border: 0px; padding: 12px 40%; text-decoration: none;\r\n");
      out.write("    display: block;\">\r\n");
      out.write("\t        <input type=\"submit\" id=\"item\" name=\"item\" value=\"의류\" style=\"color: black; border: 0px; padding: 12px 40%; text-decoration: none;\r\n");
      out.write("    display: block;\">\r\n");
      out.write("        </div>\r\n");
      out.write("        </form>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"dropdown\">\r\n");
      out.write("\t\t\t<button class=\"dropbtn\">정보</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"dropdown\">\r\n");
      out.write("\t\t\t<a href=\"event\"><button class=\"dropbtn\">이벤트</button></a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"dropdown\">\r\n");
      out.write("\t\t\t<a href=\"serviceBoard\"><button class=\"dropbtn\">고객센터</button></a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</center>\r\n");
      out.write("\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<form action=\"ProductServlet?Action=SRH\" method=\"post\">\r\n");
      out.write("\t\t<div class=\"input-group\" style=\"margin-left: 25%; width: 50%;\">\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"form-control\" name=\"text\"\r\n");
      out.write("\t\t\t\tplaceholder=\"찾을 물건을 검색하라멍!\"> <span class=\"input-group-btn\">\r\n");
      out.write("\t\t\t\t<button class=\"btn btn-secondary\" type=\"submit\">찾기</button>\r\n");
      out.write("\t\t\t</span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\r\n");
      out.write("\t<h1 style=\"margin-left: 10%;\">장바구니</h1>\r\n");
      out.write("\r\n");
      out.write("\t");

		ArrayList<ProductDTO> list = (ArrayList<ProductDTO>)session.getAttribute("list_cart");
		for (int i = 0; i < list.size(); i++) {
			ProductDTO pdto = list.get(i);
			
			String img = pdto.getPimg();
			String pname = pdto.getName();
			int price = pdto.getPrice();
			int qty = pdto.getQty();
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<hr style=\"border: 1px solid #E1E1E1;\">\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<img src=\"");
      out.print(img );
      out.write("\" width=\"15%\" style=\"margin-left: 8%;\"></img>\r\n");
      out.write("\t\t<div\r\n");
      out.write("\t\t\tstyle=\"padding: 2%; float: right; margin-right: 20%; margin-top: 3%;\">\r\n");
      out.write("\t\t\t<h4>삭제</h4>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div\r\n");
      out.write("\t\t\tstyle=\"padding: 2%; float: right; margin-right: 3%; margin-top: 3%;\">\r\n");
      out.write("\t\t\t<h4>금액합계</h4>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div\r\n");
      out.write("\t\t\tstyle=\"padding: 2%; float: right; margin-right: 3%; margin-top: 3%;\">\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<form name=\"frm\">\r\n");
      out.write("\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" name=\"ea\" class=\"form\" size=\"2\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"");
      out.print(qty );
      out.write("\" maxlength=\"2\" onblur=\"numcheck(this.form.ea.value,10)\"\r\n");
      out.write("\t\t\t\t\t\t\t\tonkeyup=\"if(isNaN(this.value)) {alert('숫자만 입력해 주세요.');this.value=''};\">\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td valign=\"middle\" height=\"30\"><input type=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"▲\" onclick=\"up(this.form.ea.value,10)\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"background-color: white; border: 0; height: 14px; font-size: 12px\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"plus\"> <br> <input type=\"button\" value=\"▼\"\r\n");
      out.write("\t\t\t\t\t\t\t\tonclick=\"down(this.form.ea.value)\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"background-color: white; border: 0; height: 14px; font-size: 12px\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"minus\"></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div\r\n");
      out.write("\t\t\tstyle=\"padding: 2%; float: right; margin-right: 3%; margin-top: 3%;\">\r\n");
      out.write("\t\t\t<h4>");
      out.print(price );
      out.write("원</h4>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div\r\n");
      out.write("\t\t\tstyle=\"padding: 2%; float: right; margin-right: 3%; margin-top: 3%;\">\r\n");
      out.write("\t\t\t<h4>");
      out.print(pname );
      out.write("</h4>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t");
 
		}
	
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<legend></legend>\r\n");
      out.write("\t\t<footer>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li>광고</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li>경숙 컴퍼니</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li>비지니스</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li>개인정보 처리방침</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li>약관</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li>설정</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
