/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.16
 * Generated at: 2017-09-20 05:15:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.zip4s.pets.dto.CustomerDTO;

public final class shopping_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.zip4s.pets.dto.CustomerDTO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <!-- Latest compiled and minified CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/style.css\">\r\n");
      out.write("    <!-- jQuery library -->\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Latest compiled JavaScript -->\r\n");
      out.write("    <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <title>Pet's</title>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <br>\r\n");
      out.write("\t");

	CustomerDTO dto = (CustomerDTO) session.getAttribute("login_info");
		if (dto == null) {
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"Nav_menu\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li><a href=\"login\"> 로그인 </a></li>\r\n");
      out.write("\t\t\t<li><a href=\"join\">회원가입</a></li>\r\n");
      out.write("\t\t\t<li>마이페이지</li>\r\n");
      out.write("\t\t\t<li>장바구니</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");

		} else {
	
      out.write("\r\n");
      out.write("\t<div id=\"Nav_menu\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li>");
      out.print(dto.getCname());
      out.write(" 님</li>\r\n");
      out.write("\t\t\t<li><a href=\"logout\"> 로그아웃 </a></li>\r\n");
      out.write("\t\t\t<li>마이페이지</li>\r\n");
      out.write("\t\t\t<li>장바구니</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");

		}
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <br>\r\n");
      out.write("\r\n");
      out.write("      <div id=\"Mainimg\">\r\n");
      out.write("        <a href=\"/pets\"><img src=\"resources/img/main.jpg\" style=\"width:50%;height:30%;\"></img></a>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <br><br>\r\n");
      out.write("\r\n");
      out.write("    <center>\r\n");
      out.write("      <div class=\"dropdown\" >\r\n");
      out.write("        <a href=\"shopping\"><button class=\"dropbtn\">쇼핑</button></a>\r\n");
      out.write("       \r\n");
      out.write("       <form id=\"itemForm\" action=\"ProductServlet?Action=ITEM\" method=\"post\">\r\n");
      out.write("        <div class=\"dropdown-content\">\r\n");
      out.write("\t        <input type=\"submit\" id=\"item\" name=\"item\" value=\"장난감\" style=\"color: black; border: 0px; padding: 12px 36%; text-decoration: none;\r\n");
      out.write("    display: block;\">\r\n");
      out.write("\t        <input type=\"submit\" id=\"item\" name=\"item\" value=\"간식\" style=\"color: black; border: 0px; padding: 12px 40%; text-decoration: none;\r\n");
      out.write("    display: block;\">\r\n");
      out.write("\t        <input type=\"submit\" id=\"item\" name=\"item\" value=\"의류\" style=\"color: black; border: 0px; padding: 12px 40%; text-decoration: none;\r\n");
      out.write("    display: block;\">\r\n");
      out.write("        </div>\r\n");
      out.write("        </form>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"dropdown\" >\r\n");
      out.write("        <a href=\"info\"><button class=\"dropbtn\">정보</button></a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"dropdown\" >\r\n");
      out.write("        <a href=\"event\"><button class=\"dropbtn\">이벤트</button></a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"dropdown\" >\r\n");
      out.write("        <a href=\"serviceBoard\"><button class=\"dropbtn\">고객센터</button></a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </center>\r\n");
      out.write("\r\n");
      out.write("    <br>\r\n");
      out.write("\r\n");
      out.write("<form action=\"ProductServlet?Action=SRH\" method=\"post\">\r\n");
      out.write("\t\t<div class=\"input-group\" style=\"margin-left: 25%; width: 50%;\">\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"form-control\" name=\"text\"\r\n");
      out.write("\t\t\t\tplaceholder=\"찾을 물건을 검색하라멍!\"> <span class=\"input-group-btn\">\r\n");
      out.write("\t\t\t\t<button class=\"btn btn-secondary\" type=\"submit\">찾기</button>\r\n");
      out.write("\t\t\t</span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t<br><br><br>\r\n");
      out.write("\r\n");
      out.write("      <div id=\"shopimg\">\r\n");
      out.write("      <div style=\"border-bottom:1px solid #cccccc;\"><h3> 장난감 </h3></div> <br>\r\n");
      out.write("      <center>\r\n");
      out.write("        <span><img src=\"resources/img/toy-1.jpg\" style=\"width:20%; height:20%;\"></span>\r\n");
      out.write("        <span><a href=\"toyinfo\"><img src=\"resources/img/toy-2.jpg\" style=\"width:20%; height:20%;\"></a></span>\r\n");
      out.write("        <span><img src=\"resources/img/toy-3.jpg\" style=\"width:20%; height:20%;\"></span>\r\n");
      out.write("        <span><img src=\"resources/img/toy-4.jpg\" style=\"width:20%; height:20%;\"></span>\r\n");
      out.write("        <div>\r\n");
      out.write("          <span>찍찍낚시</span>\r\n");
      out.write("          <span style=\"margin-left:17%; margin-right:5%;\">카샤카샤</span>\r\n");
      out.write("          <span style=\"margin-left:10%; margin-right:18%;\">문어냠얌</span>\r\n");
      out.write("          <span>꽁치꽁치</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div>\r\n");
      out.write("          <span>5,500원</span>\r\n");
      out.write("          <span style=\"margin-left:18%; margin-right:6%;\">8,500원</span>\r\n");
      out.write("          <span style=\"margin-left:10%; margin-right:18%;\">7,500원</span>\r\n");
      out.write("          <span>7,500원</span>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </center>\r\n");
      out.write("    <br><br><br><br>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"shopimg\">\r\n");
      out.write("    <div style=\"border-bottom:1px solid #cccccc;\"><h3> 애완동물 옷 </h3></div> <br>\r\n");
      out.write("    <center>\r\n");
      out.write("      <span><img src=\"resources/img/clothes-1.jpg\" style=\"width:20%; height:20%; margin:1%;\"></span>\r\n");
      out.write("      <span><img src=\"resources/img/clothes-2.jpg\" style=\"width:20%; height:20%; margin:1%;\"></span>\r\n");
      out.write("      <span><img src=\"resources/img/clothes-3.jpg\" style=\"width:20%; height:20%; margin:1%;\"></span>\r\n");
      out.write("      <span><img src=\"resources/img/clothes-4.jpg\" style=\"width:20%; height:20%; margin:1%;\"></span>\r\n");
      out.write("      <div>\r\n");
      out.write("        <span>하와이원</span>\r\n");
      out.write("        <span style=\"margin-left:18%; margin-right:6%;\">하와이투</span>\r\n");
      out.write("        <span style=\"margin-left:10%; margin-right:20%;\">스프라잇</span>\r\n");
      out.write("        <span>스프라잍</span>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div>\r\n");
      out.write("        <span>7,500원</span>\r\n");
      out.write("        <span style=\"margin-left:19%; margin-right:7%;\">4,500원</span>\r\n");
      out.write("        <span style=\"margin-left:9%; margin-right:21%;\">4,500원</span>\r\n");
      out.write("        <span>4,500원</span>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </center>\r\n");
      out.write("\r\n");
      out.write("  <br><br><br><br>\r\n");
      out.write("\r\n");
      out.write("  <div id=\"shopimg\">\r\n");
      out.write("  <div style=\"border-bottom:1px solid #cccccc;\"><h3> 간식 </h3></div> <br>\r\n");
      out.write("  <center>\r\n");
      out.write("    <span><img src=\"resources/img/food-1.jpg\" style=\"width:20%; height:20%; margin:1%;\"></span>\r\n");
      out.write("    <span><img src=\"resources/img/food-2.jpg\" style=\"width:20%; height:20%; margin:1%;\"></span>\r\n");
      out.write("    <span><img src=\"resources/img/food-3.jpg\" style=\"width:20%; height:20%; margin:1%;\"></span>\r\n");
      out.write("    <span><img src=\"resources/img/food-4.jpg\" style=\"width:20%; height:20%; margin:1%;\"></span>\r\n");
      out.write("    <div>\r\n");
      out.write("      <span>시원우유</span>\r\n");
      out.write("      <span style=\"margin-left:18%; margin-right:6%;\">츄로스으</span>\r\n");
      out.write("      <span style=\"margin-left:10%; margin-right:20%;\">치킨바나</span>\r\n");
      out.write("      <span>한우치킨</span>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div>\r\n");
      out.write("      <span>2,500원</span>\r\n");
      out.write("      <span style=\"margin-left:19%; margin-right:7%;\">2,500원</span>\r\n");
      out.write("      <span style=\"margin-left:9%; margin-right:21%;\">2,800원</span>\r\n");
      out.write("      <span>2,800원</span>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</center>\r\n");
      out.write("\r\n");
      out.write("      <br><br><br><br><br><br><br><br><br><br>\r\n");
      out.write("      <legend></legend>\r\n");
      out.write("      <footer>\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li>광고</li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li>경숙 컴퍼니</li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li>비지니스</li>\r\n");
      out.write("        </ul>\r\n");
      out.write("\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li>개인정보 처리방침</li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li>약관</li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li>설정</li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
